### SECTION 01 - 필터링 최솟값 중앙값(p.166)

In [67]:
import pandas as pd
df1 = pd.read_csv("type1_data1.csv")
df1.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [68]:
f5nz = df1['f5'] != 0
df1[f5nz].shape

(102, 10)

In [69]:
df1['views'] = df1['views'].fillna(df1['views'].min())
df1['views'].median()

5924.0

### SECTION 02 - 카테고리, 인덱스 문자열 슬라이싱(p.167)

In [70]:
import pandas as pd
df2 = pd.read_csv('type1_data1.csv')

In [71]:
df2 = df2['subscribed'].value_counts()
df2

subscribed
2025-02-17    16
2024-06-21     3
2024-04-03     2
2024-07-29     2
2024-05-28     2
              ..
2024-07-08     1
2024-07-20     1
2024-06-10     1
2024-02-01     1
2024-05-20     1
Name: count, Length: 96, dtype: int64

In [72]:
# index[0]으로 빈도수 많은 날짜 가져오기 -> [-2:0]으로 왼쪽 2자리(일수) 가져고이 -> int 정수 변환
int(df2.index[0][-2:])

17

### SECTION 03 - 파생변수, 정렬, 인덱싱 (p.168)

In [73]:
import pandas as pd
df3 = pd.read_csv('type1_data1.csv')

In [74]:
df3 = df3.dropna()
df3.shape

(70, 10)

In [75]:
df3['new'] = df3['views']/df3['f1']
df3.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208

In [76]:
# df3['new'].sort_Values(ascending=False) -> new 컬럼 값만 담긴 Series만 남아 age이 결과에 없어짐
df3 = df3.sort_values('new', ascending=False)
df3.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
83,id83,73.0,경기,50.0,1,vip,ENTP,80.138280,2024-09-26,19139.0,382.780000
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,350.461538
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,318.916667

In [77]:
int(df3.iloc[0,1])

22

### SECTION 04 - 값 변경, 정렬, 합계(p.169)

In [78]:
df4 = pd.read_csv('type1_data1.csv')

In [79]:
df4['views'] = df4['views'].fillna(0)

In [80]:
value = df4['views'].nlargest(10).iloc[-1]
value

9877.0

In [81]:
df4.loc[df4['views']>value,'views'] = value
print(int(df4['views'].sum()))

652812

### SECTION 05 - 문자열 슬라이싱, 파생변수, 평균값(p.170)

In [82]:
df5 = pd.read_csv('type1_data1.csv')

In [83]:
df5['new'] = df5['f4'].str[2:4]

In [84]:
cond = df5['new'] == 'FJ'
df5 = df5[cond]
df5

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
0,id01,2.0,서울,NaN,0,gold,ENFJ,91.297791,2024-07-16,6820.0,FJ
1,id02,9.0,서울,70.0,1,NaN,ENFJ,60.339826,2024-05-12,2534.0,FJ
4,id05,24.0,서울,85.0,2,NaN,ISFJ,29.269869,2024-03-07,1338.0,FJ
6,id07,36.3,서울,60.0,1,NaN,ISFJ,9.796378,2024-01-11,61.0,FJ
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,FJ
8,id09,3.3,서울,35.0,2,NaN,ESFJ,17.252986,2024-03-21,2764.0,FJ
13,id13,15.0,서울,68.0,0,gold,ESFJ,83.685380,2024-12-30,5643.0,FJ
18,id18,41.0,서울,87.0,2,gold,ISFJ,80.138280,2024-03-03,7933.0,FJ
24,id24,80.0,부산,44.0,0,gold,INFJ,73.586397,2024-09-11,5976.0,FJ
31,id31,86.0,부산,77.0,0,gold,ESFJ,73.586397,2024-02-11,8014.0,FJ
32,id32,25.0,부산,64.0,0,vip,ISFJ,13.049921,2024-05-24,17421.0,FJ
33,id33,47.0,부산,94.0,0,silver,ENFJ,17.252986,2024-04-02,3880.0,FJ
39,id39,56.0,부산,50.0,0,NaN,INFJ,33.308999,2024-12-22,NaN,FJ
41,id41,81.0,대구,55.0,0,gold,ENFJ,37.113739,2024-10-04,8640.0,FJ
45,id45,97.0,대구,88.0,0,gold,ENFJ,13.049921,2024-06-21,8317.0,FJ
52,id52,97.0,대구,82.0,1,gold,ISFJ,90.496999,2024-05-20,8518.0,FJ
54,id54,53.0,대구,NaN,1,gold,ENFJ,69.730313,2024-06-21,5872.0,FJ
57,id57,3.0,대구,111.0,0,silver,ISFJ,29.269869,2024-01-12,4421.0,FJ
59,id59,64.0,대구,NaN,1,silver,ESFJ,20.129444,2024-06-23,4994.0,FJ
63,id63,88.0,경기,86.0,1,silver,ISFJ,73.586397,2024-12-01,4053.0,FJ
67,id67,66.0,경기,52.0,1,NaN,ISFJ,73.586397,2024-06-17,1159.0,FJ
73,id73,90.0,경기,NaN,1,NaN,ISFJ,73.586397,2024-08-12,512.0,FJ
81,id81,86.0,경기,50.0,1,NaN,ISFJ,37.113739,2024-09-14,244.0,FJ
85,id85,83.6,경기,55.0,0,gold,INFJ,80.138280,2024-09-24,6719.0,FJ
99,id99,1.0,경기,47.0,0,gold,ESFJ,97.381034,2024-12-02,6090.0,FJ
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,FJ
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,FJ
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,FJ

In [85]:
print(round(df5['f2'].mean(),2))

0.61

In [87]:
# cond = df5['f5'].str.contains('FJ')
# df5 = df5[cond]
# print(round(df['f2'].mean(),2))

### SECTION 06 - 필터링, 분산